### ISSUE TITLE
В презентации part-1-v2.pdf , в командах (41) указан порт 8080

### ISSUE THREAD

**Issue by dosoyerim** [k8s-community/step-by-step#16]

**Comment by rumyantseva** [comment]
Спасибо! Важное замечание!
Поправила и обновила места, где были неправильные порты.
Актуальная версия слайдов [здесь](https://www.dropbox.com/sh/couuj7sex1a1nv3/AABrqtlGf3mNKH3Vwg-q5AjMa?dl=0).
